graph TD
    A[Транзакционная база данных] --> B[Модуль сбора данных]
    C[Исторические данные клиентов] --> B
    D[Данные мониторинга поведения клиентов] --> B

    B --> E[Модуль очистки данных]
    E --> G[Система автоматической проверки данных]
    G --> H[Преднастроенные шаблоны отчетов]
    G --> I[Инструменты анализа и визуализации]
    G --> J[Автоматизированные отчеты]

    H --> J
    I --> J
